id: 9eecf5247cb84fe2b664a70918c21334
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_86-The_Question_of_Maitreya_on_the_Eight_Qualities-v1
  language: bo
  author: ''
  volume: {}
